# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0004_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='tasks',
        ),
        migrations.AddField(
            model_name='variant',
            name='questions',
            field=models.ManyToManyField(to='testapp.Question'),
        ),
    ]
