# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20170317_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default='\u0412\u0430\u0440\u0438\u0430\u043d\u0442', max_length=140),
        ),
        migrations.AlterField(
            model_name='variant',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='testapp.Question'),
        ),
    ]
