# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testapp', '0006_auto_20170317_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='questions',
        ),
        migrations.AddField(
            model_name='variant',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='testapp.Task'),
        ),
    ]
