# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20170421_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='isAnswer',
        ),
    ]
