# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_answer_isanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
