# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_answer_isanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
