# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_task_answer_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041f\u0440\u0435\u0434\u043c\u0435\u0442', max_length=250)),
                ('variants', models.ManyToManyField(blank=True, to='testapp.Variant')),
            ],
        ),
    ]
